exports.Packages = {
  pkg: {
    Starter: {
      Name: 'Starter',
      Discount: '40% discount',
      Regular_price: 50,
      Sale_price: 40,
      Disk: '3GB',
      BandWidth: '15GB',
      Email: '5',
      TLD: '3 Domains',
      CPU: '2 cores',
      My_sql_db: '4 databases',
      Free_ssl: 'Yes',
      Duration: '365 days',
    },
    Business: {
      Name: 'Business',
      Discount: '30% discount',
      Regular_price: 90,
      Sale_price: 78,
      Disk: '25GB',
      BandWidth: '100GB',
      Email: 'Unlimited',
      TLD: '12 Domains',
      CPU: 'core i3',
      My_sql_db: '8 databases',
      Free_ssl: 'Yes',
      Duration: '365 days',
    },
    Premium: {
      Name: 'Premium',
      Discount: '20% discount',
      Regular_price: 150,
      Sale_price: 140,
      Disk: '400GB',
      BandWidth: 'Unmetered',
      Email: 'Unlimited',
      TLD: 'Unlimited',
      CPU: 'core i8',
      My_sql_db: 'Unlimited',
      Free_ssl: 'Yes',
      Durattion: '365 days',
    },
  },
};
